---
.github/workflows/acceptance.yml:
  beaker_fact_matrix:
    pulpcore_version:
      - "3.6"
      - "3.7"
.github/workflows/cron.yml:
  beaker_fact_matrix:
    pulpcore_version:
      - "3.6"
      - "3.7"
